name: Acceptance Tests

on: push

jobs:
  run-acceptance-tests:
    uses: hashicorp/vault-workflows-common/.github/workflows/acc-tests.yaml@21194515bc9f86198b97d6d0be0d741728f48b4d
    secrets: inherit